In [1]:
from dask.array import from_array
from numpy import array

A = array(range(36)).reshape((6,6))
d = from_array(A, chunks=(3,3))
d

dask.array<array, shape=(6, 6), dtype=int64, chunksize=(3, 3), chunktype=numpy.ndarray>

## `np.matrix`

In [2]:
from numpy import matrix

mats = d.map_blocks(matrix, chunks=(3,3))
matsc = mats.compute(scheduler="synchronous")
matsc

matrix([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])

### `axis=None`

Dask dense blocks:

In [3]:
d.sum().compute(), d.sum(keepdims=False).compute(), d.sum(keepdims=True).compute()

(630, 630, array([[630]]))

Dask np.matrix blocks:

In [4]:
mats.sum().compute(), mats.sum(keepdims=False).compute(), mats.sum(keepdims=True).compute()

(matrix([[630]]), matrix([[630]]), matrix([[630]]))

np.matrix, sans Dask:

In [5]:
matsc.sum(), matsc.sum(keepdims=False), matsc.sum(keepdims=True)

(630, 630, matrix([[630]]))

### `axis=0`

Dask dense blocks:

In [6]:
d.sum(axis=0).compute(), d.sum(axis=0, keepdims=False).compute(), d.sum(axis=0, keepdims=True).compute()

(array([ 90,  96, 102, 108, 114, 120]),
 array([ 90,  96, 102, 108, 114, 120]),
 array([[ 90,  96, 102, 108, 114, 120]]))

Dask np.matrix blocks:

In [7]:
mats.sum(axis=0).compute(), mats.sum(axis=0, keepdims=False).compute(), mats.sum(axis=0, keepdims=True).compute()

(matrix([[ 90,  96, 102, 108, 114, 120]]),
 matrix([[ 90,  96, 102, 108, 114, 120]]),
 matrix([[ 90,  96, 102, 108, 114, 120]]))

np.matrix, sans Dask:

In [8]:
matsc.sum(axis=0), matsc.sum(axis=0, keepdims=False), matsc.sum(axis=0, keepdims=True)

(matrix([[ 90,  96, 102, 108, 114, 120]]),
 matrix([[ 90,  96, 102, 108, 114, 120]]),
 matrix([[ 90,  96, 102, 108, 114, 120]]))

### `axis=1`

Dask dense blocks:

In [9]:
d.sum(axis=1).compute(), d.sum(axis=1, keepdims=False).compute(), d.sum(axis=1, keepdims=True).compute()

(array([ 15,  51,  87, 123, 159, 195]),
 array([ 15,  51,  87, 123, 159, 195]),
 array([[ 15],
        [ 51],
        [ 87],
        [123],
        [159],
        [195]]))

Dask np.matrix blocks:

In [10]:
mats.sum(axis=1).compute(), mats.sum(axis=1, keepdims=False).compute(), mats.sum(axis=1, keepdims=True).compute()

(matrix([[ 15],
         [ 51],
         [ 87],
         [123],
         [159],
         [195]]),
 matrix([[ 15],
         [ 51],
         [ 87],
         [123],
         [159],
         [195]]),
 matrix([[ 15],
         [ 51],
         [ 87],
         [123],
         [159],
         [195]]))

np.matrix, sans Dask:

In [11]:
matsc.sum(axis=1), matsc.sum(axis=1, keepdims=False), matsc.sum(axis=1, keepdims=True)

(matrix([[ 15],
         [ 51],
         [ 87],
         [123],
         [159],
         [195]]),
 matrix([[ 15],
         [ 51],
         [ 87],
         [123],
         [159],
         [195]]),
 matrix([[ 15],
         [ 51],
         [ 87],
         [123],
         [159],
         [195]]))